// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package pb_test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ItemDetailStatus int32

const (
	ItemDetail_DEFAULT  ItemDetailStatus = 0
	ItemDetail_ACTIVE   ItemDetailStatus = 1
	ItemDetail_INACTIVE ItemDetailStatus = 2
	ItemDetail_OFF      ItemDetailStatus = 2
)

var ItemDetailStatus_name = map[int32]string{
	0: "DEFAULT",
	1: "ACTIVE",
	2: "INACTIVE",
	// Duplicate value: 2: "OFF",
}

var ItemDetailStatus_value = map[string]int32{
	"DEFAULT":  0,
	"ACTIVE":   1,
	"INACTIVE": 2,
	"OFF":      2,
}

func (x ItemDetailStatus) String() string {
	return proto.EnumName(ItemDetailStatus_name, int32(x))
}

func (ItemDetailStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0, 0}
}

type ItemDetail struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Price                int32            `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
	Desc                 string           `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	Status               ItemDetailStatus `protobuf:"varint,4,opt,name=Status,proto3,enum=item.ItemDetailStatus" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ItemDetail) Reset()         { *m = ItemDetail{} }
func (m *ItemDetail) String() string { return proto.CompactTextString(m) }
func (*ItemDetail) ProtoMessage()    {}
func (*ItemDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *ItemDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemDetail.Unmarshal(m, b)
}
func (m *ItemDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemDetail.Marshal(b, m, deterministic)
}
func (m *ItemDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemDetail.Merge(m, src)
}
func (m *ItemDetail) XXX_Size() int {
	return xxx_messageInfo_ItemDetail.Size(m)
}
func (m *ItemDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ItemDetail proto.InternalMessageInfo

func (m *ItemDetail) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ItemDetail) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ItemDetail) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *ItemDetail) GetStatus() ItemDetailStatus {
	if m != nil {
		return m.Status
	}
	return ItemDetail_DEFAULT
}

func init() {
	proto.RegisterEnum("item.ItemDetailStatus", ItemDetailStatus_name, ItemDetailStatus_value)
	proto.RegisterType((*ItemDetail)(nil), "item.ItemDetail")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df) }

var fileDescriptor_6007f868cf6553df = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xca, 0x2c, 0x49, 0xcd,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0x76, 0x32, 0x72, 0x71, 0x79,
	0x96, 0xa4, 0xe6, 0xba, 0xa4, 0x96, 0x24, 0x66, 0xe6, 0x08, 0x09, 0x71, 0xb1, 0xe4, 0x25, 0xe6,
	0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac, 0x05, 0x45,
	0x99, 0xc9, 0xa9, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xac, 0x41, 0x10, 0x0e, 0x48, 0x65, 0x4a, 0x6a,
	0x71, 0xb2, 0x04, 0x33, 0x44, 0x25, 0x88, 0x2d, 0xa4, 0xcf, 0xc5, 0x16, 0x5c, 0x92, 0x58, 0x52,
	0x5a, 0x2c, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x67, 0x24, 0xae, 0x07, 0xb6, 0x0f, 0x61, 0xbe, 0x5e,
	0x31, 0x58, 0x3a, 0x08, 0xaa, 0x4c, 0xc9, 0x86, 0x8b, 0x0d, 0x22, 0x22, 0xc4, 0xcd, 0xc5, 0xee,
	0xe2, 0xea, 0xe6, 0x18, 0xea, 0x13, 0x22, 0xc0, 0x20, 0xc4, 0xc5, 0xc5, 0xe6, 0xe8, 0x1c, 0xe2,
	0x19, 0xe6, 0x2a, 0xc0, 0x28, 0xc4, 0xc3, 0xc5, 0xe1, 0xe9, 0x07, 0xe5, 0x31, 0x09, 0xb1, 0x73,
	0x31, 0xfb, 0xbb, 0xb9, 0x09, 0x30, 0x49, 0x31, 0x09, 0x30, 0x3a, 0x71, 0x46, 0xb1, 0x17, 0x24,
	0xc5, 0x97, 0xa4, 0x16, 0x97, 0x24, 0xb1, 0x81, 0xfd, 0x64, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff,
	0xdc, 0x24, 0x1c, 0xac, 0xe1, 0x00, 0x00, 0x00,
}
