// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SubstractOwner is an autogenerated mock type for the SubstractOwner type
type SubstractOwner struct {
	mock.Mock
}

// Substract provides a mock function with given fields: a, b
func (_m *SubstractOwner) Substract(a int, b int) int {
	ret := _m.Called(a, b)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(a, b)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
