// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.5.0
// source: req.proto

package pb_test

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RichTextItem_Type int32

const (
	RichTextItem_RT_None RichTextItem_Type = 0
	RichTextItem_RT_Font RichTextItem_Type = 1
	RichTextItem_RT_Img  RichTextItem_Type = 2
)

// Enum value maps for RichTextItem_Type.
var (
	RichTextItem_Type_name = map[int32]string{
		0: "RT_None",
		1: "RT_Font",
		2: "RT_Img",
	}
	RichTextItem_Type_value = map[string]int32{
		"RT_None": 0,
		"RT_Font": 1,
		"RT_Img":  2,
	}
)

func (x RichTextItem_Type) Enum() *RichTextItem_Type {
	p := new(RichTextItem_Type)
	*p = x
	return p
}

func (x RichTextItem_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RichTextItem_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_req_proto_enumTypes[0].Descriptor()
}

func (RichTextItem_Type) Type() protoreflect.EnumType {
	return &file_req_proto_enumTypes[0]
}

func (x RichTextItem_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RichTextItem_Type.Descriptor instead.
func (RichTextItem_Type) EnumDescriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{2, 0}
}

// 对齐方式
type RichTextItem_AlignType int32

const (
	RichTextItem_AT_None   RichTextItem_AlignType = 0
	RichTextItem_AT_TOP    RichTextItem_AlignType = 1
	RichTextItem_AT_CENTER RichTextItem_AlignType = 2
	RichTextItem_AT_BOTTOM RichTextItem_AlignType = 3
)

// Enum value maps for RichTextItem_AlignType.
var (
	RichTextItem_AlignType_name = map[int32]string{
		0: "AT_None",
		1: "AT_TOP",
		2: "AT_CENTER",
		3: "AT_BOTTOM",
	}
	RichTextItem_AlignType_value = map[string]int32{
		"AT_None":   0,
		"AT_TOP":    1,
		"AT_CENTER": 2,
		"AT_BOTTOM": 3,
	}
)

func (x RichTextItem_AlignType) Enum() *RichTextItem_AlignType {
	p := new(RichTextItem_AlignType)
	*p = x
	return p
}

func (x RichTextItem_AlignType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RichTextItem_AlignType) Descriptor() protoreflect.EnumDescriptor {
	return file_req_proto_enumTypes[1].Descriptor()
}

func (RichTextItem_AlignType) Type() protoreflect.EnumType {
	return &file_req_proto_enumTypes[1]
}

func (x RichTextItem_AlignType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RichTextItem_AlignType.Descriptor instead.
func (RichTextItem_AlignType) EnumDescriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{2, 1}
}

type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query   string            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Headers map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_req_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *Request) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReqQuery string               `protobuf:"bytes,1,opt,name=req_query,json=reqQuery,proto3" json:"req_query,omitempty"`
	X        *ItemDetail          `protobuf:"bytes,2,opt,name=x,proto3" json:"x,omitempty"`
	Succ     bool                 `protobuf:"varint,3,opt,name=succ,proto3" json:"succ,omitempty"`
	Time     *timestamp.Timestamp `protobuf:"bytes,4,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_req_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetReqQuery() string {
	if x != nil {
		return x.ReqQuery
	}
	return ""
}

func (x *Response) GetX() *ItemDetail {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *Response) GetSucc() bool {
	if x != nil {
		return x.Succ
	}
	return false
}

func (x *Response) GetTime() *timestamp.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

// 富文本协议
type RichTextItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type RichTextItem_Type `protobuf:"varint,1,opt,name=type,proto3,enum=req.RichTextItem_Type" json:"type,omitempty"`
	// Types that are assignable to Item:
	//	*RichTextItem_ItemFont
	//	*RichTextItem_ItemImg
	Item      isRichTextItem_Item    `protobuf_oneof:"item"`
	AlignType RichTextItem_AlignType `protobuf:"varint,4,opt,name=align_type,json=alignType,proto3,enum=req.RichTextItem_AlignType" json:"align_type,omitempty"`
}

func (x *RichTextItem) Reset() {
	*x = RichTextItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RichTextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichTextItem) ProtoMessage() {}

func (x *RichTextItem) ProtoReflect() protoreflect.Message {
	mi := &file_req_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichTextItem.ProtoReflect.Descriptor instead.
func (*RichTextItem) Descriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{2}
}

func (x *RichTextItem) GetType() RichTextItem_Type {
	if x != nil {
		return x.Type
	}
	return RichTextItem_RT_None
}

func (m *RichTextItem) GetItem() isRichTextItem_Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (x *RichTextItem) GetItemFont() *Font {
	if x, ok := x.GetItem().(*RichTextItem_ItemFont); ok {
		return x.ItemFont
	}
	return nil
}

func (x *RichTextItem) GetItemImg() *Img {
	if x, ok := x.GetItem().(*RichTextItem_ItemImg); ok {
		return x.ItemImg
	}
	return nil
}

func (x *RichTextItem) GetAlignType() RichTextItem_AlignType {
	if x != nil {
		return x.AlignType
	}
	return RichTextItem_AT_None
}

type isRichTextItem_Item interface {
	isRichTextItem_Item()
}

type RichTextItem_ItemFont struct {
	ItemFont *Font `protobuf:"bytes,2,opt,name=item_font,json=itemFont,proto3,oneof"`
}

type RichTextItem_ItemImg struct {
	ItemImg *Img `protobuf:"bytes,3,opt,name=item_img,json=itemImg,proto3,oneof"`
}

func (*RichTextItem_ItemFont) isRichTextItem_Item() {}

func (*RichTextItem_ItemImg) isRichTextItem_Item() {}

type Font struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text  string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Size  int32  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Color string `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *Font) Reset() {
	*x = Font{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Font) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Font) ProtoMessage() {}

func (x *Font) ProtoReflect() protoreflect.Message {
	mi := &file_req_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Font.ProtoReflect.Descriptor instead.
func (*Font) Descriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{3}
}

func (x *Font) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Font) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Font) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Img struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// 放缩比例，e.g.100（%），200%
	ScaleRatio int32 `protobuf:"varint,2,opt,name=scale_ratio,json=scaleRatio,proto3" json:"scale_ratio,omitempty"`
}

func (x *Img) Reset() {
	*x = Img{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Img) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Img) ProtoMessage() {}

func (x *Img) ProtoReflect() protoreflect.Message {
	mi := &file_req_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Img.ProtoReflect.Descriptor instead.
func (*Img) Descriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{4}
}

func (x *Img) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Img) GetScaleRatio() int32 {
	if x != nil {
		return x.ScaleRatio
	}
	return 0
}

type RichTextObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*RichTextItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *RichTextObj) Reset() {
	*x = RichTextObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RichTextObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichTextObj) ProtoMessage() {}

func (x *RichTextObj) ProtoReflect() protoreflect.Message {
	mi := &file_req_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichTextObj.ProtoReflect.Descriptor instead.
func (*RichTextObj) Descriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{5}
}

func (x *RichTextObj) GetItems() []*RichTextItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MockPanicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MockPanicReq) Reset() {
	*x = MockPanicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MockPanicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockPanicReq) ProtoMessage() {}

func (x *MockPanicReq) ProtoReflect() protoreflect.Message {
	mi := &file_req_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockPanicReq.ProtoReflect.Descriptor instead.
func (*MockPanicReq) Descriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{6}
}

type MockPanicRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MockPanicRsp) Reset() {
	*x = MockPanicRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_req_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MockPanicRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockPanicRsp) ProtoMessage() {}

func (x *MockPanicRsp) ProtoReflect() protoreflect.Message {
	mi := &file_req_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockPanicRsp.ProtoReflect.Descriptor instead.
func (*MockPanicRsp) Descriptor() ([]byte, []int) {
	return file_req_proto_rawDescGZIP(), []int{7}
}

var File_req_proto protoreflect.FileDescriptor

var file_req_proto_rawDesc = []byte{
	0x0a, 0x09, 0x72, 0x65, 0x71, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x65, 0x71,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x15, 0x69, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x5f, 0x70, 0x6b, 0x67, 0x2f, 0x69, 0x74,
	0x65, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa0, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x33, 0x0a, 0x07, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x65,
	0x71, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x1a,
	0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x4a, 0x04, 0x08, 0x0f, 0x10,
	0x10, 0x4a, 0x04, 0x08, 0x09, 0x10, 0x0c, 0x52, 0x02, 0x68, 0x61, 0x22, 0xa1, 0x01, 0x0a, 0x08,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x5f,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x71,
	0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x01, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x69, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x01, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x75, 0x63, 0x63, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x04, 0x73, 0x75, 0x63, 0x63, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x69, 0x6d,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x4a, 0x04, 0x08, 0x0f, 0x10, 0x10, 0x4a,
	0x04, 0x08, 0x09, 0x10, 0x0c, 0x52, 0x03, 0x66, 0x6f, 0x6f, 0x52, 0x03, 0x62, 0x61, 0x72, 0x22,
	0xc1, 0x02, 0x0a, 0x0c, 0x52, 0x69, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x49, 0x74, 0x65, 0x6d,
	0x12, 0x2a, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x72, 0x65, 0x71, 0x2e, 0x52, 0x69, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x49, 0x74, 0x65,
	0x6d, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x09,
	0x69, 0x74, 0x65, 0x6d, 0x5f, 0x66, 0x6f, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x72, 0x65, 0x71, 0x2e, 0x46, 0x6f, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x08, 0x69, 0x74,
	0x65, 0x6d, 0x46, 0x6f, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69,
	0x6d, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x72, 0x65, 0x71, 0x2e, 0x49,
	0x6d, 0x67, 0x48, 0x00, 0x52, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x6d, 0x67, 0x12, 0x3a, 0x0a,
	0x0a, 0x61, 0x6c, 0x69, 0x67, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1b, 0x2e, 0x72, 0x65, 0x71, 0x2e, 0x52, 0x69, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x2e, 0x41, 0x6c, 0x69, 0x67, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09,
	0x61, 0x6c, 0x69, 0x67, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x22, 0x2c, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x0b, 0x0a, 0x07, 0x52, 0x54, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x52, 0x54, 0x5f, 0x46, 0x6f, 0x6e, 0x74, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52,
	0x54, 0x5f, 0x49, 0x6d, 0x67, 0x10, 0x02, 0x22, 0x42, 0x0a, 0x09, 0x41, 0x6c, 0x69, 0x67, 0x6e,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x54, 0x5f, 0x4e, 0x6f, 0x6e, 0x65, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x54, 0x5f, 0x54, 0x4f, 0x50, 0x10, 0x01, 0x12, 0x0d, 0x0a,
	0x09, 0x41, 0x54, 0x5f, 0x43, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x41, 0x54, 0x5f, 0x42, 0x4f, 0x54, 0x54, 0x4f, 0x4d, 0x10, 0x03, 0x42, 0x06, 0x0a, 0x04, 0x69,
	0x74, 0x65, 0x6d, 0x22, 0x44, 0x0a, 0x04, 0x46, 0x6f, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73,
	0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x22, 0x38, 0x0a, 0x03, 0x49, 0x6d, 0x67,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x5f, 0x72, 0x61, 0x74, 0x69,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x52, 0x61,
	0x74, 0x69, 0x6f, 0x22, 0x36, 0x0a, 0x0b, 0x52, 0x69, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x4f,
	0x62, 0x6a, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x72, 0x65, 0x71, 0x2e, 0x52, 0x69, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74,
	0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x0e, 0x0a, 0x0c, 0x4d,
	0x6f, 0x63, 0x6b, 0x50, 0x61, 0x6e, 0x69, 0x63, 0x52, 0x65, 0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x4d,
	0x6f, 0x63, 0x6b, 0x50, 0x61, 0x6e, 0x69, 0x63, 0x52, 0x73, 0x70, 0x32, 0x69, 0x0a, 0x09, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x53, 0x53, 0x12, 0x27, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x12, 0x0c, 0x2e, 0x72, 0x65, 0x71, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x0d, 0x2e, 0x72, 0x65, 0x71, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x33, 0x0a, 0x09, 0x4d, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x6e, 0x69, 0x63, 0x12, 0x11,
	0x2e, 0x72, 0x65, 0x71, 0x2e, 0x4d, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x6e, 0x69, 0x63, 0x52, 0x65,
	0x71, 0x1a, 0x11, 0x2e, 0x72, 0x65, 0x71, 0x2e, 0x4d, 0x6f, 0x63, 0x6b, 0x50, 0x61, 0x6e, 0x69,
	0x63, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x70, 0x62, 0x5f, 0x74,
	0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_req_proto_rawDescOnce sync.Once
	file_req_proto_rawDescData = file_req_proto_rawDesc
)

func file_req_proto_rawDescGZIP() []byte {
	file_req_proto_rawDescOnce.Do(func() {
		file_req_proto_rawDescData = protoimpl.X.CompressGZIP(file_req_proto_rawDescData)
	})
	return file_req_proto_rawDescData
}

var file_req_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_req_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_req_proto_goTypes = []interface{}{
	(RichTextItem_Type)(0),      // 0: req.RichTextItem.Type
	(RichTextItem_AlignType)(0), // 1: req.RichTextItem.AlignType
	(*Request)(nil),             // 2: req.Request
	(*Response)(nil),            // 3: req.Response
	(*RichTextItem)(nil),        // 4: req.RichTextItem
	(*Font)(nil),                // 5: req.Font
	(*Img)(nil),                 // 6: req.Img
	(*RichTextObj)(nil),         // 7: req.RichTextObj
	(*MockPanicReq)(nil),        // 8: req.MockPanicReq
	(*MockPanicRsp)(nil),        // 9: req.MockPanicRsp
	nil,                         // 10: req.Request.HeadersEntry
	(*ItemDetail)(nil),          // 11: item.ItemDetail
	(*timestamp.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_req_proto_depIdxs = []int32{
	10, // 0: req.Request.headers:type_name -> req.Request.HeadersEntry
	11, // 1: req.Response.x:type_name -> item.ItemDetail
	12, // 2: req.Response.time:type_name -> google.protobuf.Timestamp
	0,  // 3: req.RichTextItem.type:type_name -> req.RichTextItem.Type
	5,  // 4: req.RichTextItem.item_font:type_name -> req.Font
	6,  // 5: req.RichTextItem.item_img:type_name -> req.Img
	1,  // 6: req.RichTextItem.align_type:type_name -> req.RichTextItem.AlignType
	4,  // 7: req.RichTextObj.items:type_name -> req.RichTextItem
	2,  // 8: req.SearchSSS.Search:input_type -> req.Request
	8,  // 9: req.SearchSSS.MockPanic:input_type -> req.MockPanicReq
	3,  // 10: req.SearchSSS.Search:output_type -> req.Response
	9,  // 11: req.SearchSSS.MockPanic:output_type -> req.MockPanicRsp
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_req_proto_init() }
func file_req_proto_init() {
	if File_req_proto != nil {
		return
	}
	file_inside_pkg_item_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_req_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_req_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_req_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RichTextItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_req_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Font); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_req_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Img); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_req_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RichTextObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_req_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MockPanicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_req_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MockPanicRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_req_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*RichTextItem_ItemFont)(nil),
		(*RichTextItem_ItemImg)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_req_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_req_proto_goTypes,
		DependencyIndexes: file_req_proto_depIdxs,
		EnumInfos:         file_req_proto_enumTypes,
		MessageInfos:      file_req_proto_msgTypes,
	}.Build()
	File_req_proto = out.File
	file_req_proto_rawDesc = nil
	file_req_proto_goTypes = nil
	file_req_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchSSSClient is the client API for SearchSSS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchSSSClient interface {
	Search(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	MockPanic(ctx context.Context, in *MockPanicReq, opts ...grpc.CallOption) (*MockPanicRsp, error)
}

type searchSSSClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchSSSClient(cc grpc.ClientConnInterface) SearchSSSClient {
	return &searchSSSClient{cc}
}

func (c *searchSSSClient) Search(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/req.SearchSSS/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchSSSClient) MockPanic(ctx context.Context, in *MockPanicReq, opts ...grpc.CallOption) (*MockPanicRsp, error) {
	out := new(MockPanicRsp)
	err := c.cc.Invoke(ctx, "/req.SearchSSS/MockPanic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchSSSServer is the server API for SearchSSS service.
type SearchSSSServer interface {
	Search(context.Context, *Request) (*Response, error)
	MockPanic(context.Context, *MockPanicReq) (*MockPanicRsp, error)
}

// UnimplementedSearchSSSServer can be embedded to have forward compatible implementations.
type UnimplementedSearchSSSServer struct {
}

func (*UnimplementedSearchSSSServer) Search(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (*UnimplementedSearchSSSServer) MockPanic(context.Context, *MockPanicReq) (*MockPanicRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MockPanic not implemented")
}

func RegisterSearchSSSServer(s *grpc.Server, srv SearchSSSServer) {
	s.RegisterService(&_SearchSSS_serviceDesc, srv)
}

func _SearchSSS_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchSSSServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/req.SearchSSS/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchSSSServer).Search(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchSSS_MockPanic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MockPanicReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchSSSServer).MockPanic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/req.SearchSSS/MockPanic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchSSSServer).MockPanic(ctx, req.(*MockPanicReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchSSS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "req.SearchSSS",
	HandlerType: (*SearchSSSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchSSS_Search_Handler,
		},
		{
			MethodName: "MockPanic",
			Handler:    _SearchSSS_MockPanic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "req.proto",
}
