// Code generated by protoc-gen-go. DO NOT EDIT.
// source: req.proto

package pb_test

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	Query                string            `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Request) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

type Response struct {
	ReqQuery             string      `protobuf:"bytes,1,opt,name=req_query,json=reqQuery,proto3" json:"req_query,omitempty"`
	X                    *ItemDetail `protobuf:"bytes,2,opt,name=x,proto3" json:"x,omitempty"`
	Succ                 bool        `protobuf:"varint,3,opt,name=succ,proto3" json:"succ,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_a52bd445c288993d, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetReqQuery() string {
	if m != nil {
		return m.ReqQuery
	}
	return ""
}

func (m *Response) GetX() *ItemDetail {
	if m != nil {
		return m.X
	}
	return nil
}

func (m *Response) GetSucc() bool {
	if m != nil {
		return m.Succ
	}
	return false
}

func init() {
	proto.RegisterType((*Request)(nil), "req.Request")
	proto.RegisterMapType((map[string]string)(nil), "req.Request.HeadersEntry")
	proto.RegisterType((*Response)(nil), "req.Response")
}

func init() {
	proto.RegisterFile("req.proto", fileDescriptor_a52bd445c288993d)
}

var fileDescriptor_a52bd445c288993d = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x3d, 0x4f, 0xf3, 0x30,
	0x10, 0xc7, 0x1f, 0xc7, 0x7d, 0xda, 0xe4, 0x5a, 0x44, 0x64, 0x31, 0x84, 0x22, 0xa1, 0x28, 0x0b,
	0x99, 0x32, 0xa4, 0x0c, 0xa8, 0x23, 0x02, 0x09, 0xba, 0xe1, 0x6c, 0x2c, 0x95, 0x13, 0x0e, 0xa5,
	0xa2, 0x6d, 0xe2, 0x97, 0xa0, 0xf6, 0xdb, 0xf0, 0x51, 0x51, 0xec, 0x56, 0x0a, 0xdb, 0xfd, 0x7c,
	0xf6, 0xff, 0xc5, 0x10, 0x28, 0x94, 0x59, 0xab, 0x1a, 0xd3, 0x30, 0xaa, 0x50, 0xce, 0x61, 0x63,
	0x70, 0xe7, 0x0e, 0x92, 0x1f, 0x02, 0x13, 0x8e, 0xb2, 0x43, 0x6d, 0xd8, 0x15, 0xfc, 0x97, 0x1d,
	0xaa, 0x63, 0x44, 0x62, 0x92, 0x06, 0xdc, 0x01, 0x5b, 0xc0, 0xa4, 0x46, 0xf1, 0x81, 0x4a, 0x47,
	0x5e, 0x4c, 0xd3, 0x69, 0x7e, 0x9d, 0xf5, 0x7a, 0xa7, 0x47, 0xd9, 0x8b, 0xdb, 0x3d, 0xef, 0x8d,
	0x3a, 0xf2, 0xf3, 0xcd, 0xf9, 0x12, 0x66, 0xc3, 0x05, 0x0b, 0x81, 0x7e, 0xe1, 0x59, 0xb8, 0x1f,
	0x7b, 0xb3, 0x6f, 0xb1, 0xed, 0x30, 0xf2, 0x9c, 0x99, 0x85, 0xa5, 0xf7, 0x40, 0x56, 0x23, 0xff,
	0x32, 0x0c, 0x57, 0x23, 0x3f, 0x08, 0x67, 0xdc, 0xab, 0x45, 0x22, 0xc1, 0xe7, 0xa8, 0xdb, 0x66,
	0xaf, 0x91, 0xdd, 0xd8, 0x32, 0xeb, 0x61, 0x4c, 0x5f, 0xa1, 0x7c, 0xb3, 0x49, 0x6f, 0x81, 0x1c,
	0xac, 0xdc, 0x34, 0x0f, 0x33, 0xdb, 0xf1, 0xd5, 0xe0, 0xee, 0x09, 0x8d, 0xd8, 0x6c, 0x39, 0x39,
	0x30, 0x06, 0x23, 0xdd, 0x55, 0x55, 0x44, 0x63, 0x92, 0xfa, 0xdc, 0xce, 0x7f, 0xcc, 0xe8, 0x67,
	0xd3, 0x70, 0x5a, 0x0a, 0x95, 0xdf, 0x43, 0x50, 0xa0, 0x50, 0x55, 0x5d, 0x14, 0x05, 0xbb, 0x83,
	0xb1, 0x03, 0x36, 0x1b, 0x36, 0x9f, 0x5f, 0x9c, 0xc8, 0x45, 0x4b, 0xfe, 0x3d, 0x06, 0xef, 0x93,
	0xb6, 0x5c, 0x1b, 0xd4, 0xa6, 0x1c, 0xdb, 0xdf, 0x5d, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0x01,
	0x54, 0xf4, 0xb8, 0x7b, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SearchSSSClient is the client API for SearchSSS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchSSSClient interface {
	Search(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type searchSSSClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchSSSClient(cc grpc.ClientConnInterface) SearchSSSClient {
	return &searchSSSClient{cc}
}

func (c *searchSSSClient) Search(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/req.SearchSSS/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchSSSServer is the server API for SearchSSS service.
type SearchSSSServer interface {
	Search(context.Context, *Request) (*Response, error)
}

// UnimplementedSearchSSSServer can be embedded to have forward compatible implementations.
type UnimplementedSearchSSSServer struct {
}

func (*UnimplementedSearchSSSServer) Search(ctx context.Context, req *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}

func RegisterSearchSSSServer(s *grpc.Server, srv SearchSSSServer) {
	s.RegisterService(&_SearchSSS_serviceDesc, srv)
}

func _SearchSSS_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchSSSServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/req.SearchSSS/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchSSSServer).Search(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _SearchSSS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "req.SearchSSS",
	HandlerType: (*SearchSSSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchSSS_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "req.proto",
}
